django_blog/blog/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from blog.views import SignUpView, ProfileView, PostListView, PostDetailView, PostUpdateView, PostDeleteView, \
    PostCreateView, CommentCreateView, CommentUpdateView, CommentDeleteView, CommentListView, search_list, PostByTagListView

urlpatterns = [
    path('login/', LoginView.as_view(template_name='blog/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', SignUpView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('post/', PostListView.as_view(), name='post-list'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('post/<int:post_id>/comments/', CommentListView.as_view(), name='comment-list'),
    path('post/<int:pk>/comments/new/', CommentCreateView.as_view(), name='comment-create'),
    path('comment/<int:pk>/update/', CommentUpdateView.as_view(), name='comment-update'),
    path('comment/<int:pk>/delete/', CommentDeleteView.as_view(), name='comment-delete'),
    path('/search/', search_list, name='search'),
    path('tags/<slug:tag_slug>/', PostByTagListView.as_view(), name='tag-list'),

]

django_blog/django_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
]

django_blog/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    published_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    tags = TaggableManager()

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField()
    profile_pic = models.ImageField(upload_to="profile_pic", null=True, blank=True)
    def __str__(self):
        return self.user.username

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Tag(models.Model):
    name = models.CharField(max_length=100)
    posts = models.ManyToManyField(Post)
    def __str__(self):
        return self.name
# Create your models here.

django_blog/blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import models
from django.contrib.auth.models import User
from taggit.forms import TagWidget

from blog.models import Post, Comment

class SignUpForm(UserCreationForm):
    email = forms.EmailField()

class BlogPostForm(forms.ModelForm):
    title = forms.CharField(max_length=100)
    content = forms.CharField(widget=forms.Textarea)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    tags = forms.CharField(widget=TagWidget())
    class Meta:
        model = Post
        fields = ['title', 'content', 'author', 'tags']
        widgets = {
            'tags': TagWidget(),
        }

class CommentForm(forms.ModelForm):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = forms.CharField(widget=forms.Textarea)
    class Meta:
        model = Comment
        fields = ['author', 'content']

django_blog/blog/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView
from .forms import SignUpForm
from django.http import request
from .models import UserProfile, Post, Comment, Tag
from django.db import models
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.db.models import Q

class SignUpView(CreateView):
    form_class = SignUpForm
    template_name = 'blog/register.html'

class ProfileView(LoginRequiredMixin, CreateView):
    if request.method == 'POST':
        userpersona = UserProfile.objects.get(user=request.user)
        userpersona.email = models.EmailField()
        userpersona.profile_pic = models.ImageField(upload_to="profile_pic", null=True, blank=True)
        userpersona.save()

class PostListView(ListView):
    model = Post
    template_name = 'blog/post_list.html'

class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'

@login_required(login_url='login')
class PostCreateView(CreateView):
    model = Post
    template_name = 'blog/post_form.html'
    fields = ['title', 'content']
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(PostCreateView, self).form_valid(form)

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    template_name = 'blog/post_form.html'
    fields = ['title', 'content']
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(PostUpdateView, self).form_valid(form)
    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    template_name = 'blog/post_confirm_delete.html'
    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author

class CommentListView(ListView):
    model = Comment
    template_name = 'blog/post_detail.html'

@login_required(login_url='login')
class CommentCreateView(CreateView):
    model = Comment
    template_name = 'blog/post_detail.html'
    fields = ['content']
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(CommentCreateView, self).form_valid(form)

class CommentUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Comment
    template_name = 'blog/post_detail.html'
    fields = ['content']
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(CommentUpdateView, self).form_valid(form)

class CommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Comment
    template_name = 'blog/post_detail.html'

class PostByTagListView(ListView):
    model = Post
    template_name = 'blog/post_list.html'

def search_list(request):
    query = request.GET.get('q')
    if query:
        posts = Post.objects.filter(title__icontains=query)
        tags = Post.objects.filter(tags__name__icontains=query)
        contents = Post.objects.filter(content__icontains=query)
    else:
        posts = Post.objects.all()
        tags = Tag.objects.all()
    return render(request, 'blog/post_search.html', {'posts': posts, 'tags': tags, 'contents': contents})

django_blog/blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Django Blog{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="{% url 'home' %}">Home</a></li>
                <li><a href="{% url 'posts' %}">Blog Posts</a></li>
                <li><a href="{% url 'login' %}">Login</a></li>
                <li><a href="{% url 'register' %}">Register</a></li>
            </ul>
        </nav>
    </header>

    <div class="content">
        {% block content %}
        <!-- Page-specific content goes here -->
        {% endblock %}
    </div>

    <footer>
        <p>&copy; 2024 Django Blog</p>
    </footer>

    <script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>

django_blog/blog/templates/blog/login.html
{% extends 'base.html' %}
{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

<form method="post" action="{% url 'login' %}">
    {% csrf_token %} {{ form.as_p }}

    <input type="submit" value="login" />
</form>

django_blog/blog/templates/blog/post_confirm_delete.html
{% extends 'base.html' %}
{% block title %}Create/Edit Post{% endblock %} {% block content %}
<h2>Delete Post</h2>
<p>Do you want to delete this post?</p>

django_blog/blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% block title %}Post Details{% endblock %}
{% block content %}
  <h1>Post Details</h1>
  <ul>
    {% for post in post_list %}
      <li>{{ post.title }} by {{ post.author }}</li>
      <p>{{ post.content }}</p>
    {% endfor %}
  </ul>
  <ul>
    {% for comment in comment_list %}
      <li>{{ comment.content }} by {{ post.author }}</li>
    {% endfor %}
  </ul>
  <form method="post">
    {% csrf_token %} {{ form }}
    <button type="submit">Submit</button>
  </form>
{% endblock %}

django_blog/blog/templates/blog/post_form.html
{% extends 'base.html' %}
{% if user.is_authenticated %}
{% block title %}Create/Edit Post{% endblock %} {% block content %}
<h2>Create/Edit Post</h2>
<form method="post">
    {% csrf_token %} {{ form }}
    <button type="submit">Submit</button>
</form>
{% endblock %}

django_blog/blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% block title %}Posts{% endblock %}
{% block content %}
  <h1>Posts</h1>
  <ul>
    {% for posts in post_list %}
      <li>{{ post.title }} by {{ post.author }}</li>
    {% endfor %}
    </ul>
{% endblock %}

django_blog/blog/templates/blog/post_search.html
<form method="get">
    <input type="text" name="q" placeholder="Search..." value="{{ request.GET.q }}">
    <button type="submit">Search</button>
</form>

<ul>
  {% for post in posts %}
    <li>{{ post.title }}</li>
  {% empty %}
    <li>No results found.</li>
  {% endfor %}
</ul>

django_blog/blog/templates/blog/profile.html
{% if user.is_authenticated %} You are logged in as {{ user }}.
<form action="{% url 'logout' %}" method="post">
    {% csrf_token %}
    <button type="submit">Log Out</button>
</form>
{% else %} You are not logged in.
<a href="{% url 'login' %}">Click here to log in.</a>
{% endif %}

django_blog/blog/templates/blog/register.html
{% extends 'base.html' %}
{% block title %}Sign Up{% endblock %} {% block content %}
<h2>Sign up</h2>
<form method="post">
    {% csrf_token %} {{ form }}
    <button type="submit">Sign Up</button>
</form>
{% endblock %}